server:
  port: 8597
  servlet:
    context-path: /api/v1/training

spring:
  application:
    name: training-service
    
  datasource:
    url: jdbc:postgresql://localhost:5433/training
    username: postgres
    password: postgres
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
    initialization-mode: never
    platform: 
  jpa:
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: none
      
# FLYWAY (FlywayProperties)
  flyway:
    baseline-on-migrate: true
    clean-on-validation-error: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://127.0.0.1:8762/eureka}
  instance:
    preferIpAddress: true


