server:
  port: 8597
  servlet:
    context-path: /api/v1/training

spring:
  application:
    name: training-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://127.0.0.1:8762/eureka}
  instance:
    preferIpAddress: true


